services:
  app:
    build: .
    # restart: unless-stopped
    env_file:
      - .env.development
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres:latest
    # restart: unless-stopped
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
